# Generated by Django 3.0.7 on 2020-06-23 17:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phrasebox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), size=None)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='phrasebox',
            constraint=models.UniqueConstraint(fields=('id', 'username'), name='unique_pb_id_user'),
        ),
    ]
