# Generated by Django 3.0.4 on 2020-06-05 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versions',
            name='owner',
        ),
    ]
