# Generated by Django 3.0.4 on 2020-06-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0002_remove_versions_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
