# Generated by Django 3.0.4 on 2020-06-05 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='track_name')),
                ('key', models.CharField(max_length=2, null=True, verbose_name='track_key')),
                ('lyrics', models.CharField(max_length=6000, null=True, verbose_name='track_lyrics')),
                ('modify_date', models.DateTimeField()),
                ('version', models.PositiveIntegerField()),
                ('private', models.BooleanField(default=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
