# Generated by Django 3.0.4 on 2020-06-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20200605_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
